### ISSUE TITLE
Test.py file

### ISSUE THREAD

**Issue by 1991viet** [hyperlex/vdcnn#1]
Hi,
Thank you for your nice code. But could you update the file test.py. Currently if I train the model by running the train.py script, it works fine. But then I run the test.py to evaluate model on test set, it doesnot work. Some parts are missing includes:
The FLAG variable (I could copy it from the train.py, but do I need to change drop from 0.5 to 1.0 in test file)
cnn variable is not defined in test.py file
Thank you

**Comment by Touila** [comment]
Hi , 
Indeed when i separated the training and testing steps i forgot to copy the flags in test.py. 
In what concerns the dropout flag, if you check the vdcnn class you will see that i didnt use dropout for conv layers(i used it once to test then removed it). 
I will change the code to remove the "cnn variable not found" error.
Thank you

**Comment by 1991viet** [comment]
Thank you so much :)
